operator -> ax_cli "Runs commands (launch, attach, takeover, fork, sync)"
ax_cli -> local_db "Reads/writes index"
ax_cli -> storage "Reads/writes records and blobs"
daemon -> local_db "Reads/writes index"
daemon -> storage "Syncs records and blobs"
ax_cli -> terminal "Runs 'ax pane' wrapper in durable pane"
tb_session -> terminal "Provides task-board abstraction inside terminal"
ax_cli -> tb_session "Imports/exports opaque session bundles (Bridge Contract)"
ax_cli -> providers "Launches and orchestrates transactions via JSON-over-stdio"
providers -> native_stores "Materializes native state as directed by ax"
ax_cli -> mesh "Executes RPC (ax rpc serve --stdio) via SSH"
daemon -> mesh "Periodically synchronizes across mesh"
