operator -> ax_cli "Browses, selects, confirms, launches, and attaches"
automation -> ax_cli "Submits typed projected reads and guarded mutations"
ax_cli -> directory_controller "Queries and confirms exact directory plans"
directory_controller -> catalog "Reads deterministic catalog and freshness"
directory_controller -> lineage "Reads evidence-backed conversation lineage"
directory_controller -> enrichment "Plans and schedules exact-head enrichment"
directory_controller -> continuation "Plans and executes confirmed continuations"
catalog -> lineage "Supplies current instances and immutable evidence"
catalog -> local_db "Rebuilds derived catalog and search index"
catalog -> storage "Reads immutable observations and batches"
lineage -> storage "Reads links, resolutions, clone, and fork evidence"
enrichment -> directory_node "Requests bounded source-local history projections"
enrichment -> enrichment_worker "Runs typed jobs without mutation authority"
enrichment_worker -> enrichment "Returns schema-validated annotation candidates"
enrichment -> storage "Publishes immutable requests, receipts, and annotations"
directory_node -> native_stores "Reads allowlisted source-local metadata and exact heads"
directory_node -> storage "Publishes sanitized immutable directory records"
continuation -> directory_node "Revalidates source and target facts"
continuation -> cloning "Delegates cross-environment continuation"
continuation -> terminal_controller "Delegates managed activation or ownership-neutral attach"
continuation -> providers "Delegates existing AX ownership and provider effects"
cloning -> providers "Uses Provider 2 and companion Session Adapter 1 transactions"
cloning -> storage "Publishes clone evidence and lineage"
ax_cli -> local_db "Reads/writes index"
ax_cli -> storage "Reads/writes records and blobs"
daemon -> local_db "Reads/writes index"
daemon -> storage "Syncs records and blobs"
daemon -> directory_node "Schedules source-local inventory and health"
daemon -> enrichment "Schedules policy-permitted enrichment"
daemon -> aqua_broker "Contacts existing broker only"
ax_cli -> terminal_controller "Requests AX-authorized create, attach, reconnect, stop, or restore"
ax_cli -> aqua_broker "Realm/auth evidence"
aqua_broker -> tmux_backend "Creates/attests dedicated private -S server on macOS"
terminal_controller -> terminal_registry "Resolves and admits a conforming implementation"
terminal_registry -> tmux_backend "Registers built-in Unix implementation"
terminal_registry -> conpty_backend "Registers built-in native-Windows implementation"
terminal_controller -> terminal_backend "Delegates authorized host-local operations"
tmux_backend -> terminal_backend "Implements"
conpty_backend -> terminal_backend "Implements"
terminal_controller -> pane_entrypoint "Supplies authorized LogicalSession and provider context"
tmux_backend -> pane_entrypoint "Hosts exactly ax pane SESSION_ID"
conpty_backend -> pane_entrypoint "Hosts exactly ax pane SESSION_ID"
pane_entrypoint -> providers "Invokes provider lifecycle only through AX authorization"
terminal_controller -> storage "Owns logical session, lease/fencing, workspace, checkpoint, and evidence state"
terminal_controller -> tb_session "Owns task-board integration; backend has no task-board authority"
terminal_controller -> mesh "Owns replication and takeover; presentation transport carries no authority"
tb_session -> terminal_backend "Presents inside one host-local TerminalInstance without changing ownership"
ax_cli -> tb_session "Imports/exports opaque session bundles (Bridge Contract)"
ax_cli -> providers "Launches and orchestrates transactions via JSON-over-stdio"
providers -> native_stores "Materializes native state as directed by ax"
ax_cli -> mesh "Executes RPC (ax rpc serve --stdio) via SSH"
daemon -> mesh "Periodically synchronizes across mesh"
storage -> mesh "Exchanges allowlisted immutable namespaces, including directory_record"
